// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWfP22Zy1mjuI-i3qqGaKLBRDBrXP4_U4',
    appId: '1:237461301408:web:6b47ab9d5707d0b1e541c5',
    messagingSenderId: '237461301408',
    projectId: 'songbook-f75fd',
    authDomain: 'songbook-f75fd.firebaseapp.com',
    storageBucket: 'songbook-f75fd.firebasestorage.app',
    measurementId: 'G-EJSCWXHN4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-NOVLcorB7iKYoO36tMSS1-pmOiV5vpI',
    appId: '1:237461301408:android:790cf4d54aa16a64e541c5',
    messagingSenderId: '237461301408',
    projectId: 'songbook-f75fd',
    storageBucket: 'songbook-f75fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_YFDVwRQ09lGWaebkeIRArj2H8YjuEBs',
    appId: '1:237461301408:ios:ba23404189b06a69e541c5',
    messagingSenderId: '237461301408',
    projectId: 'songbook-f75fd',
    storageBucket: 'songbook-f75fd.firebasestorage.app',
    androidClientId: '237461301408-02rs79d4ha5o9s5biqnodc66m0rtf9ef.apps.googleusercontent.com',
    iosClientId: '237461301408-870qe4fufcbhtl0g671semqish7kshsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_YFDVwRQ09lGWaebkeIRArj2H8YjuEBs',
    appId: '1:237461301408:ios:ba23404189b06a69e541c5',
    messagingSenderId: '237461301408',
    projectId: 'songbook-f75fd',
    storageBucket: 'songbook-f75fd.firebasestorage.app',
    androidClientId: '237461301408-02rs79d4ha5o9s5biqnodc66m0rtf9ef.apps.googleusercontent.com',
    iosClientId: '237461301408-870qe4fufcbhtl0g671semqish7kshsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWfP22Zy1mjuI-i3qqGaKLBRDBrXP4_U4',
    appId: '1:237461301408:web:64f79b4178e19318e541c5',
    messagingSenderId: '237461301408',
    projectId: 'songbook-f75fd',
    authDomain: 'songbook-f75fd.firebaseapp.com',
    storageBucket: 'songbook-f75fd.firebasestorage.app',
    measurementId: 'G-9EST799HT1',
  );
}
